export const bannerData = {
    title: "Properties",
    description:
        "Perfection lies not only in buildings and spaces but in immersive experiences that inspire, transform, and integrate communities. We deliver lasting value to our customers and stakeholders, always with an ambition for no less than the extraordinary.",
    image: "/images/property/banner.jpg",
};

export const properties = [
    {
      id: "1",
      image: "/images/community-listing/card2.jpg",
      hoverImage: "/images/community-listing/hoverimg.png",
      status: "Completed",
      location: "Downtown Dubai, UAE",
      title: "COVE<br>BY IMTIAZ",
      subtitle: "Spacious Community Living",
      href: "/projects/cove-by-imtiaz",
      startingFrom: "AED 3.5 M",
      units: "1BR - 3BR",
      date: "2024-08-02",
      propertyType: "Villa",
      community: "",
      latitude: "25.1972",
      longitude: "55.2744",
    },
    {
      id: "2",
      image: "/images/community-listing/card2.jpg",
      hoverImage: "/images/community-listing/hoverimg.png",
      status: "Completed",
      location: "Downtown Dubai, UAE",
      title: "COVE<br>BY IMTIAZ",
      subtitle: "Spacious Community Living",
      href: "/projects/cove-by-imtiaz",
      startingFrom: "AED 3.5 M",
      units: "1BR - 3BR",
      date: "2024-08-02",
      propertyType: "",
      community: "",
      latitude: "25.1955",
      longitude: "55.2760",
    },
    {
      id: "3",
      image: "/images/community-listing/card2.jpg",
      hoverImage: "/images/community-listing/hoverimg.png",
      status: "Available",
      location: "Dubai Marina, UAE",
      title: "AZURE\nRESIDENCES",
      subtitle: "Waterfront Luxury Living",
      href: "/projects/azure-residences",
      startingFrom: "AED 3.5 M",
      units: "1BR - 3BR",
      date: "2024-08-02",
      propertyType: "",
      community: "Waterfront",
      latitude: "25.0800",
      longitude: "55.1400",
    },
    {
      id: "4",
      image: "/images/community-listing/card2.jpg",
      hoverImage: "/images/community-listing/hoverimg.png",
      status: "Upcoming",
      location: "Business Bay, UAE",
      title: "SKYLINE\nTOWER",
      subtitle: "Urban Living Redefined",
      href: "/projects/skyline-tower",
      startingFrom: "AED 3.5 M",
      units: "1BR - 3BR",
      date: "2024-08-02",
      propertyType: "",
      community: "",
      latitude: "25.1850",
      longitude: "55.2600",
    },
    {
      id: "5",
      image: "/images/community-listing/card2.jpg",
      hoverImage: "/images/community-listing/hoverimg.png",
      status: "Completed",
      location: "Palm Jumeirah, UAE",
      title: "PALM\nVILLAS",
      subtitle: "Exclusive Island Retreat",
      href: "/projects/palm-villas",
      startingFrom: "AED 3.5 M",
      units: "1BR - 3BR",
      date: "2024-08-02",
      propertyType: "",
      community: "",
      latitude: "25.1124",
      longitude: "55.1386",
    },
    {
      id: "6",
      image: "/images/community-listing/card2.jpg",
      hoverImage: "/images/community-listing/hoverimg.png",
      status: "Ongoing",
      location: "Jumeirah, UAE",
      title: "PEARL\nESTATES",
      subtitle: "Refined Coastal Elegance",
      href: "/projects/pearl-estates",
      startingFrom: "AED 3.5 M",
      units: "1BR - 3BR",
      date: "2024-08-02",
      propertyType: "",
      community: "",
      latitude: "25.2048",
      longitude: "55.2708",
    },
    {
      id: "7",
      image: "/images/community-listing/card2.jpg",
      hoverImage: "/images/community-listing/hoverimg.png",
      status: "Upcoming",
      location: "DIFC, UAE",
      title: "DISTRICT\nONE",
      subtitle: "Premium City Residences",
      href: "/projects/district-one",
      startingFrom: "AED 3.5 M",
      units: "1BR - 3BR",
      date: "2024-08-02",
      propertyType: "",
      community: "",
      latitude: "25.2136",
      longitude: "55.2796",
    },
  ];

export const projectsData = [
    {
        id:"1",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Completed",
        location: "Down Town Dubai, UAE",
        title: "COVE<br>BY IMTIAZ",
        subtitle: "Spacious Community Living",
        href: "/projects/cove-by-imtiaz",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
    },
    {
        id:"2",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Ongoing",
        location: "Dubai Marina, UAE",
        title: "AZURE\nRESIDENCES",
        subtitle: "Waterfront Luxury Living",
        href: "/projects/azure-residences",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
    },
    {
        id:"3",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Upcoming",
        location: "Business Bay, UAE",
        title: "SKYLINE\nTOWER",
        subtitle: "Urban Living Redefined",
        href: "/projects/skyline-tower",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
    },
    {
        id:"4",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Completed",
        location: "Palm Jumeirah, UAE",
        title: "PALM\nVILLAS",
        subtitle: "Exclusive Island Retreat",
        href: "/projects/palm-villas",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
    },
    {
        id:"5",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Ongoing",
        location: "Jumeirah, UAE",
        title: "PEARL\nESTATES",
        subtitle: "Refined Coastal Elegance",
        href: "/projects/pearl-estates",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
    },
    {
        id:"6",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Upcoming",
        location: "DIFC, UAE",
        title: "DISTRICT\nONE",
        subtitle: "Premium City Residences",
        href: "/projects/district-one",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
    },
];