export const offPlanBannerData = {
  image: "/images/off-plan/banner.jpg",
  title: "Off-Plan Properties",
  description:
    "Discover Premium Off-Plan Developments with Flexible Payment Plans",
  buttonText: "schedule visit",
  buttonLink: "#",
};

export const faqData = {
  title: "FAQ",
  subtitle:
    "Lorem Ipsum is simply dummy text of the printing and\ntypesetting industry. Lorem Ipsum has",
  items: [
    {
      id: "faq-1",
      question: "What are off-plan properties?",
      answer:
        "Off-plan properties are residential or commercial units that are sold before construction is completed. Buyers purchase based on architectural plans and developer reputation, with flexible payment schedules typically linked to construction milestones",
    },
    {
      id: "faq-2",
      question: "What makes your brand unique?",
      answer:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled",
    },
    {
      id: "faq-3",
      question: "Who are your properties designed for?",
      answer:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled",
    },
    {
      id: "faq-4",
      question: "How do you ensure quality and longevity?",
      answer:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled",
    },
    {
      id: "faq-5",
      question: "Is sustainability part of your vision?",
      answer:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled",
    },
  ],
};

export const whyInvestData = {
  title: "Why Invest in Off Plan\nProperties in Dubai",
  description: `<p>Investing in off-plan properties in Dubai offers numerous advantages for both end-users and investors. The competitive pricing, flexible payment plans, and high potential for capital appreciation make it an attractive investment destination in Dubai's dynamic real estate market.</p> <p>With ongoing infrastructure development and proximity to major business districts, Dubai continues to attract professionals, families, and investors looking for premium properties with excellent rental yields and long-term value growth potential.</p>`,
};


// data.ts
export const offPlanProperties = [
    {
        id: "1",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Under Construction",
        location: "Downtown Dubai, UAE",
        title: "WYNWOOD HORIZON<br>BY IMTIAZ",
        subtitle: "Luxury Urban Living",
        href: "/projects/wynwood-horizon",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
        date: "2024-08-02",
        propertyType: "Apartment",
        community: "Downtown",
        latitude: "25.1972",
        longitude: "55.2744",
    },
    {
        id: "2",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Off Plan",
        location: "Downtown Dubai, UAE",
        title: "SUNSET BAY 5<br>BY IMTIAZ",
        subtitle: "Waterfront Living In Dubai",
        href: "/projects/sunset-bay-5",
        startingFrom: "AED 3.5 M",
        units: "1BR - 2BR",
        date: "2024-08-01",
        propertyType: "Apartment",
        community: "Waterfront",
        latitude: "25.1955",
        longitude: "55.2760",
    },
    {
        id: "3",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Off Plan",
        location: "Downtown Dubai, UAE",
        title: "COVE<br>BY IMTIAZ",
        subtitle: "Spacious Community Living",
        href: "/projects/cove-by-imtiaz",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
        date: "2024-07-30",
        propertyType: "Villa",
        community: "Downtown",
        latitude: "25.1972",
        longitude: "55.2750",
    },
    {
        id: "4",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Completed",
        location: "Downtown Dubai, UAE",
        title: "PEARL HOUSE<br>BY IMTIAZ",
        subtitle: "Family-Friendly Community",
        href: "/projects/pearl-house",
        startingFrom: "AED 2.8 M",
        units: "1BR - 4BR",
        date: "2024-07-28",
        propertyType: "Townhouse",
        community: "Downtown",
        latitude: "25.1960",
        longitude: "55.2730",
    },
    {
        id: "5",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Off Plan",
        location: "Downtown Dubai, UAE",
        title: "BEACH WALK GRAND 2<br>BY IMTIAZ",
        subtitle: "Waterfront Living In Dubai",
        href: "/projects/beach-walk-grand-2",
        startingFrom: "AED 4.0 M",
        units: "2BR - 4BR",
        date: "2024-07-25",
        propertyType: "Apartment",
        community: "Waterfront",
        latitude: "25.0800",
        longitude: "55.1400",
    },
    {
        id: "6",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Off Plan",
        location: "Downtown Dubai, UAE",
        title: "WYNWOOD HORIZON<br>BY IMTIAZ",
        subtitle: "Luxury Urban Living",
        href: "/projects/wynwood-horizon-2",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
        date: "2024-07-22",
        propertyType: "Apartment",
        community: "Downtown",
        latitude: "25.1850",
        longitude: "55.2600",
    },
    {
        id: "7",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Off Plan",
        location: "Downtown Dubai, UAE",
        title: "WYNWOOD HORIZON<br>BY IMTIAZ",
        subtitle: "Luxury Urban Living",
        href: "/projects/wynwood-horizon-3",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
        date: "2024-07-20",
        propertyType: "Apartment",
        community: "Downtown",
        latitude: "25.1124",
        longitude: "55.1386",
    },
    {
        id: "8",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Completed",
        location: "Downtown Dubai, UAE",
        title: "COVE EDITION<br>BY IMTIAZ",
        subtitle: "Spacious Community Living",
        href: "/projects/cove-edition",
        startingFrom: "AED 3.5 M",
        units: "1BR - 3BR",
        date: "2024-07-18",
        propertyType: "Villa",
        community: "Downtown",
        latitude: "25.2048",
        longitude: "55.2708",
    },
    {
        id: "9",
        image: "/images/community-listing/card2.jpg",
        hoverImage: "/images/community-listing/hoverimg.png",
        status: "Off Plan",
        location: "Downtown Dubai, UAE",
        title: "SUNSET BAY 4<br>BY IMTIAZ",
        subtitle: "Waterfront Living In Dubai",
        href: "/projects/sunset-bay-4",
        startingFrom: "AED 3.2 M",
        units: "1BR - 2BR",
        date: "2024-07-15",
        propertyType: "Apartment",
        community: "Waterfront",
        latitude: "25.2136",
        longitude: "55.2796",
    },
];